apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: temp-team-a
  description: Temp Team A
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: divgupta@redhat.com
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: divyanshigupta
spec:
  profile:
    # Intentional no displayName for testing
    email: divgupta@redhat.com
  memberOf: [temp-team-a]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nationalparks-py
  labels: 
    backstage.io/kubernetes-id: nationalparks-py
    component: nationalparks-py
  annotations:
    github.com/project-slug: divyanshiGupta/nationalparks-py
    backstage.io/kubernetes-id: nationalparks-py
spec:
  type: service
  lifecycle: unknown
  owner: temp-team-a
