apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: eswaraiahsapram
  namespace: default
spec:
  profile:
    displayName: Eswar S
    email: esapram@redhat.com
  memberOf: [group:default/red-hat]
