apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: eswaraiahsapram
spec:
  profile:
    displayName: Eswar S
    email: esapram@redhat.com
  memberOf: [temp-team-a]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: National Parks
  name: nationalparks-py
  labels: 
    component: nationalparks-py
  tags:
    - rhdh
    - plugin
    - homepage
    - ui
  annotations:
    github.com/project-slug: redhat-developer/rhdh-plugins
    jira/project-key: RHIDP
    backstage.io/kubernetes-id: nationalparks-py
    janus-idp.io/tekton: nationalparks-py
    # backstage.io/kubernetes-namespace: div
  description: The Petstore API allows you to manage pet data, user accounts, and store orders through simple CRUD operations, ideal for testing RESTful API functionality.
spec:
  type: service
  lifecycle: unknown
  owner: temp-team-a
