apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: temp-team-a
  description: Temp Team A
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: esapram@redhat.com
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Eswaraiahsapram
spec:
  profile:
    # Intentional no displayName for testing
    email: esapram@redhat.com
    displayName: Eswar S
  memberOf: [temp-team-a]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nationalparks-py
  labels: 
    component: nationalparks-py
  annotations:
    github.com/project-slug: divyanshiGupta/nationalparks-py
    backstage.io/kubernetes-id: nationalparks-py
    janus-idp.io/tekton: nationalparks-py
    # backstage.io/kubernetes-namespace: div
spec:
  type: service
  lifecycle: unknown
  owner: temp-team-a
